export const timeZones = [
    "UTC (Universal Time Coordinated) GMT+0:00",
    "PST (Pacific Standard Time) GMT-8:00",
    "EST (Eastern Standard Time) GMT-5:00",
    "CST (Central Standard Time) GMT-6:00",
    "MST (Mountain Standard Time) GMT-7:00",
    "GMT (Greenwich Mean Time) GMT+0:00",
    "CET (Central European Time) GMT+1:00",
    "EET (Eastern European Time) GMT+2:00",
    "IST (Indian Standard Time) GMT+5:30",
    "AEST (Australian Eastern Standard Time) GMT+10:00",
    "ACST (Australian Central Standard Time) GMT+9:30",
    "AWST (Australian Western Standard Time) GMT+8:00",
    "JST (Japan Standard Time) GMT+9:00",
    "KST (Korea Standard Time) GMT+9:00",
    "HKT (Hong Kong Time) GMT+8:00",
    "SGT (Singapore Time) GMT+8:00",
    "NZST (New Zealand Standard Time) GMT+12:00",
    "AST (Atlantic Standard Time) GMT-4:00",
    "AKST (Alaska Standard Time) GMT-9:00",
    "HST (Hawaii Standard Time) GMT-10:00",
    "WET (Western European Time) GMT+0:00",
    "SAST (South Africa Standard Time) GMT+2:00",
    "BST (British Summer Time) GMT+1:00",
    "PDT (Pacific Daylight Time) GMT-7:00",
    "EDT (Eastern Daylight Time) GMT-4:00",
    "CST (China Standard Time) GMT+8:00",
    "MSK (Moscow Standard Time) GMT+3:00",
    "AEDT (Australian Eastern Daylight Time) GMT+11:00",
    "NZDT (New Zealand Daylight Time) GMT+13:00",
];


export const languages = [
    "English US",
    "English UK",
    "Spanish",
    "French",
    "German",
    "Italian",
    "Portuguese (Brazil)",
    "Portuguese (Portugal)",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "Japanese",
    "Korean",
    "Hindi",
    "Bengali",
    "Russian",
    "Arabic",
    "Urdu",
    "Turkish",
    "Vietnamese",
    "Thai",
    "Malay",
    "Dutch",
    "Swedish",
    "Norwegian",
    "Danish",
    "Finnish",
    "Polish",
    "Czech",
    "Greek",
    "Hungarian",
    "Romanian",
    "Hebrew",
    "Indonesian",
    "Filipino",
    "Punjabi",
    "Tamil",
    "Telugu",
    "Gujarati",
    "Marathi",
];